### ISSUE TITLE
Double quoted version in longhorn bundle

### ISSUE THREAD

**Issue by Orhideous** [kairos-io/community-bundles#28]
This
```yaml
longhorn:
  values:
    defaultSettings:
      backupstorePollInterval: 600
  version: 1.4.0
```
Turned into this (`/var/lib/rancher/k3s/server/manifests/longhorn.yaml`)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart: longhorn
  repo: https://charts.longhorn.io
  valuesContent: |-
    {"defaultSettings":{"backupstorePollInterval":600}}
  version: ""1.4.0""
```

---

```bash
alpha:~$ getConfig longhorn.version
"1.4.0"

alpha:~$ kairos-agent config get longhorn.version
1.4.0
```
